### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by dhcai21** [xiaoluo91/Strainline#1]
Dear Xiao Luo,

I run Strainline on the data in the "example" folder with the following command:

> ./Strainline-master/src/strainline.sh -i ./Strainline-master/example/reads.fa -o test -p ont -t 128

But I encountered a problem shown as follow: 

> [V] using kmer range [8,8]
[V] creating KmerLimit for k=8...done.
[V] graph structures set up MemUsage(size=8516.46,rss=2419.07,peak=8625.32)
./Strainline-master/src/strainline.sh: line 331:  7834 Segmentation fault      (core dumped) daccord -t$threads $las_file reads.dam >> corrected.0.fa

Could you please help me fix this problem?

Thanks!

Dehan

**Comment by xiaoluo91** [comment]
Hi, could you try to use fewer cores to run (for example, -t 32 or -t 8) on this small example dataset ? sometimes the read error correction tool 'daccord' causes 'segmentation fault' if using too many cores.

**Comment by dhcai21** [comment]
Hi Xiao, 
Thanks for the reply! I have tried the tool using different numbers of cores, i.e. 1, and 8. But I still have the same problem, the "segmentation fault"

**Comment by xiaoluo91** [comment]
ok, could you show me the files 'reads.*las' and 'reads.dam', are they empty or not ?

**Comment by xiaoluo91** [comment]
Hi, the reason is probably due to the version of daccord. You could have a look at the documentation(I have updated it) of using daccord. You should check your daccord version and make sure use daccord-0.0.10, so, please follow the new instructions and it should work.

**Comment by dhcai21** [comment]
Hi Xiao,
I reinstall the Daccord with version 0.0.10 according to your advice (I used version 0.0.14 previously). Now I can run the tool normally. Thanks!
